/*
 * File: UserInterface.java
 * -------------------
 * This file contains the MainGUI class, which implements the GUI for
 * the Quine-McCluskey Solver application.
 *
 * Author: Shana Galman
 * Version: 1.0
 * Date: April 11, 2024
 *
 * Description:
 * This class provides the graphical user interface for the Quine-McCluskey Solver.
 * It allows users to input minterms and variables, solve the expression using
 * the Quine-McCluskey method, and view the results.
 */


import java.awt.*;
import java.awt.event.ActionEvent;

import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;


public class UserInterface extends javax.swing.JFrame {

    /**
     * Constructor of the UserInterface class.
     * Initializes the UI components and sets the background color to white.
     */

    public UserInterface() {
        initComponents();

        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * Method to initialize the UI components.
     * This method is automatically generated by the IDE and contains the code
     * for creating and positioning the UI elements.
     */

    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        results = new javax.swing.JLabel();
        minterms = new javax.swing.JLabel();
        vars = new javax.swing.JLabel();
        varTxt = new javax.swing.JTextField();
        mintermsTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSolution = new javax.swing.JTextArea();
        customVars = new javax.swing.JCheckBox();
        defaultVars = new javax.swing.JLabel();
        spaceCommaSeparated = new javax.swing.JLabel();
        qmTitle = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        solveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        aboutSeparator = new javax.swing.JSeparator();
        about = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quine-McCluskey Method Simulation");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(470, 470));
        setPreferredSize(new java.awt.Dimension(880, 480));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        results.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        results.setText("Output:");
        results.setName("results"); // NOI18N
        getContentPane().add(results);
        results.setBounds(230, 230, 200, 22);

        minterms.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minterms.setText("Input Minterms:");
        minterms.setName("minterms"); // NOI18N
        getContentPane().add(minterms);
        minterms.setBounds(40, 90, 170, 22);

        vars.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vars.setText("Variables:");
        vars.setName("vars"); // NOI18N
        getContentPane().add(vars);
        vars.setBounds(450, 90, 100, 22);

        varTxt.setFont(new java.awt.Font("Gotham", 2, 14)); // NOI18N
        varTxt.setForeground(new java.awt.Color(0, 0, 0));
        varTxt.setText("   A, B, C, D, E, F, G, H, I, J");
        varTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        varTxt.setEnabled(false);
        varTxt.setName("varTxt"); // NOI18N
        varTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varTxtActionPerformed(evt);
            }
        });
        getContentPane().add(varTxt);
        varTxt.setBounds(450, 120, 360, 30);

        mintermsTxt.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        mintermsTxt.setName("mintermsTxt"); // NOI18N
        getContentPane().add(mintermsTxt);
        mintermsTxt.setBounds(40, 120, 380, 30);

        txaSolution.setEditable(false);
        txaSolution.setColumns(20);
        txaSolution.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txaSolution.setLineWrap(true);
        txaSolution.setRows(5);
        txaSolution.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txaSolution.setName("txaSolution"); // NOI18N
        jScrollPane1.setViewportView(txaSolution);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 260, 420, 110);

        customVars.setBackground(new java.awt.Color(255, 255, 255));
        customVars.setFont(new java.awt.Font("Gotham", 2, 10)); // NOI18N
        customVars.setForeground(new java.awt.Color(0, 0, 0));
        customVars.setText("customize variables");
        customVars.setName("cbCustom"); // NOI18N
        customVars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customVarsActionPerformed(evt);
            }
        });
        getContentPane().add(customVars);
        customVars.setBounds(690, 150, 120, 20);

        defaultVars.setFont(new java.awt.Font("Gotham", 2, 10)); // NOI18N
        defaultVars.setForeground(new java.awt.Color(102, 102, 102));
        defaultVars.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        defaultVars.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        defaultVars.setName("lblMinSubs"); // NOI18N
        defaultVars.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(defaultVars);
        defaultVars.setBounds(530, 100, 280, 20);

        spaceCommaSeparated.setFont(new java.awt.Font("Gotham", 2, 10)); // NOI18N
        spaceCommaSeparated.setForeground(new java.awt.Color(102, 102, 102));
        spaceCommaSeparated.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        spaceCommaSeparated.setText("NOTE: space or comma delimited*");
        spaceCommaSeparated.setName("spaceCommaSeparated"); // NOI18N
        getContentPane().add(spaceCommaSeparated);
        spaceCommaSeparated.setBounds(140, 100, 280, 16);

        qmTitle.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        qmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qmTitle.setText("QUINE-MCCLUSKEY TABULATION METHOD SOLVER");
        qmTitle.setName("qmTitle"); // NOI18N
        getContentPane().add(qmTitle);
        qmTitle.setBounds(100, 10, 660, 50);
        getContentPane().add(separator);
        separator.setBounds(50, 220, 780, 10);

        solveButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        solveButton.setText("SOLVE");
        solveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solveButton.setName("solveButton"); // NOI18N
        solveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solveButtonMouseClicked(evt);
            }
        });
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(solveButton);
        solveButton.setBounds(370, 170, 140, 40);

        clearButton.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.setMaximumSize(new java.awt.Dimension(67, 29));
        clearButton.setMinimumSize(new java.awt.Dimension(67, 29));
        clearButton.setName("clearButton"); // NOI18N
        clearButton.setPreferredSize(new java.awt.Dimension(67, 29));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(370, 380, 130, 30);

        label.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        label.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(label);
        label.setBounds(460, 440, 80, 16);


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(ActionEvent evt) {
    }

    private void solveButtonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_solveButtonMouseClicked

        String minterms = mintermsTxt.getText();
        boolean mintermsValid = false;
        spaceCommaSeparated.setForeground(new Color(0, 0, 0));
        spaceCommaSeparated.setText("space or comma delimited*");

        defaultVars.setForeground(new Color(0, 0, 0));
        if (customVars.isSelected()){
            defaultVars.setText("enter 10 variables, space and comma separated*");
        } else {
            defaultVars.setText("default variables used*");
        }

        if (!isValidMinterms(minterms)){
            spaceCommaSeparated.setForeground(new Color(0, 0, 0));
            spaceCommaSeparated.setText("input exceeds maximum value 1024*");
        } else {
            mintermsValid = true;
        }

        String variables = varTxt.getText();
        if (!minterms.isBlank()){
            QuineMcCluskeyMethod s = new QuineMcCluskeyMethod(minterms);
            s.solve();
            if (mintermsValid && minterms.matches("[\\d,\\s]+"))
                txaSolution.setText(s.printResults(convertVariables(variables)));
        }
    }//GEN-LAST:event_solveButtonMouseClicked

    private void clearButtonMouseClicked(MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked

        mintermsTxt.setText("");
        varTxt.setText("A, B, C, D, E, F, G, H, I, J");
        customVars.setSelected(false);
        varTxt.setEnabled(false);
        txaSolution.setText("");

        defaultVars.setForeground(new Color(0, 0, 0));
        defaultVars.setText("Default variables used*");

        spaceCommaSeparated.setForeground(new Color(24, 24, 24));
        spaceCommaSeparated.setText("NOTE: Delimit using space and/or comma");
    }//GEN-LAST:event_clearButtonMouseClicked

    private void customVarsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_customVarsActionPerformed

        if (customVars.isSelected()){
            defaultVars.setText("Enter 10 variables. Space and comma delimited");
            varTxt.setEnabled(true);
            varTxt.setText("");
        }
        else{
            defaultVars.setText("Default variables used*");
            varTxt.setEnabled(false);
            varTxt.setText("A, B, C, D, E, F, G, H, I, J");
        }
    }//GEN-LAST:event_customVarsActionPerformed

    private void aboutMouseClicked(MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        JOptionPane.showMessageDialog(null, "CMSC 130 Machine Problem No. 1 \nQuine-McCluskey Method Simulation \n\nDeveloped by: \nAbogado, Marxel S. \nHaboc, Carla Joy G. \n\nSubmitted to: \nMa'am Avegail D. Carpio", "About this program", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMouseClicked

    private void clearButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

    }//GEN-LAST:event_clearButtonActionPerformed

    private void varTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varTxtActionPerformed

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }


    public String[] convertVariables(String s){
        s = s.replace(",", " "); //for comma-delimited inputs
        String[] variables = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"};
        if (s.trim().equals("")) {
            // if empty
            return variables;
        }
        String[] a = s.trim().split(" +");
        String[] t = new String[a.length];
        // array of minterms
        if (t.length < 10)
            defaultVars.setText("Note: Variables missing! Using default for the rest.");
        for (int i = 0; i < t.length; i++) {
            try {
                if (a[i].length() > 1)
                    variables[i] = "(" + a[i] + ")";
                else
                    variables[i] = a[i];
            } catch (Exception e) {
                defaultVars.setForeground(new Color(0, 0, 0));
                defaultVars.setText("Input exceeds 10 variables! Using only the first 10 vars.");

            }
        }
        return variables;
    }


    public boolean isValidMinterms(String s){
        s = s.replace(",", " ");
        String[] temp = s.trim().split(" +");
        int[] intMinterms = new int[temp.length];
        for (int i = 0; i < temp.length; i++){
            try {intMinterms[i] = Integer.parseInt(temp[i]);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Invalid input. Please try again!!", "Error Message", JOptionPane.ERROR_MESSAGE);
                mintermsTxt.setText("");
            }
        }
        for (int i = 0; i < intMinterms.length; i++){
            if (intMinterms[i] > 1023)
                return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JSeparator aboutSeparator;
    private javax.swing.JButton clearButton;
    private javax.swing.JCheckBox customVars;
    private javax.swing.JLabel defaultVars;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel minterms;
    private javax.swing.JTextField mintermsTxt;
    private javax.swing.JLabel qmTitle;
    private javax.swing.JLabel results;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton solveButton;
    private javax.swing.JLabel spaceCommaSeparated;
    private javax.swing.JTextArea txaSolution;
    private javax.swing.JTextField varTxt;
    private javax.swing.JLabel vars;
    // End of variables declaration//GEN-END:variables
}
